'use strict';

// setup.js handles @clerk/express stubbing and DB connection.
// Use global.clerkMock to control auth state per-test.

const chai    = require('chai');
const request = require('supertest');
const fs      = require('fs');
const path    = require('path');
const sharp   = require('sharp');

const { expect } = chai;

const ProductGroup = require('../models/ProductGroup');
const AssetType    = require('../models/AssetType');
const Asset        = require('../models/Asset');
const app          = require('../server');

// Seed helpers
const mkGroup = (name = 'Laptops') =>
  ProductGroup.create({ name });

const mkType = (groupId, name = 'MacBook Pro') =>
  AssetType.create({ groupId, name });

const mkAsset = (typeId, name = 'Unit 001', status = 'Available') =>
  Asset.create({ typeId, name, status });

// Test image buffer — generated by sharp, guaranteed valid
let MINI_JPEG;

before(async () => {
  MINI_JPEG = await sharp({
    create: { width: 20, height: 20, channels: 3, background: { r: 255, g: 0, b: 0 } },
  }).jpeg().toBuffer();
});

// Cleanup helpers
const uploadsDir = path.join(__dirname, '..', 'uploads');

const cleanUploads = async () => {
  try {
    const dirs = ['groups', 'types', 'assets'];
    for (const dir of dirs) {
      const dirPath = path.join(uploadsDir, dir);
      try {
        const files = await fs.promises.readdir(dirPath);
        for (const file of files) {
          await fs.promises.unlink(path.join(dirPath, file));
        }
      } catch (_) { /* dir may not exist yet */ }
    }
  } catch (_) { /* uploads/ may not exist yet */ }
};

describe('Photo Upload API', () => {

  afterEach(async () => {
    await Promise.all([
      ProductGroup.deleteMany({}),
      AssetType.deleteMany({}),
      Asset.deleteMany({}),
      cleanUploads(),
    ]);
    clerkMock.reset();
  });

  // ── Upload photo ────────────────────────────────────────────────────────────

  describe('POST /api/groups/:id/photo', () => {
    it('uploads a photo for a group and sets imageUrl/thumbnailUrl', async () => {
      const group = await mkGroup('Laptops');

      const res = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');

      expect(res.status).to.equal(200);
      expect(res.body.imageUrl).to.match(/^\/uploads\/groups\/.+/);
      expect(res.body.thumbnailUrl).to.match(/^\/uploads\/groups\/.+/);
      // Verify DB was updated
      const updated = await ProductGroup.findById(group.id);
      expect(updated.imageUrl).to.equal(res.body.imageUrl);
      expect(updated.thumbnailUrl).to.equal(res.body.thumbnailUrl);
      // Verify files exist on disk
      const imgPath = path.join(uploadsDir, 'groups', path.basename(res.body.imageUrl));
      const thumbPath = path.join(uploadsDir, 'groups', path.basename(res.body.thumbnailUrl));
      expect(fs.existsSync(imgPath)).to.be.true;
      expect(fs.existsSync(thumbPath)).to.be.true;
    });

    it('replaces an existing photo (old files deleted, new ones saved)', async () => {
      const group = await mkGroup('Laptops');

      // Upload first photo
      const res1 = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'first.jpg');
      expect(res1.status).to.equal(200);

      // Upload second photo — same entity, so URL is the same (ID-based filename)
      const res2 = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'second.jpg');
      expect(res2.status).to.equal(200);
      // Same entity → same ID-based filename → same URL
      expect(res2.body.imageUrl).to.equal(res1.body.imageUrl);

      // Files should exist with the new content
      const imgPath = path.join(uploadsDir, 'groups', path.basename(res2.body.imageUrl));
      expect(fs.existsSync(imgPath)).to.be.true;

      // DB should have the URL set
      const updated = await ProductGroup.findById(group.id);
      expect(updated.imageUrl).to.equal(res2.body.imageUrl);
    });

    it('returns 400 when no file is attached', async () => {
      const group = await mkGroup();

      const res = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .send({});
      expect(res.status).to.equal(400);
    });

    it('returns 400 for invalid file type', async () => {
      const group = await mkGroup();

      const res = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', Buffer.from('not an image'), { filename: 'test.txt', contentType: 'text/plain' });
      expect(res.status).to.equal(400);
      expect(res.body.message).to.include('Invalid file type');
    });

    it('returns 403 when user is not admin', async () => {
      clerkMock.setRole('customer');
      const group = await mkGroup();

      const res = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');
      expect(res.status).to.equal(403);
    });

    it('returns 401 when unauthenticated', async () => {
      clerkMock.setAuth(null);
      const group = await mkGroup();

      const res = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');
      expect(res.status).to.equal(401);
    });
  });

  // ── Delete photo ────────────────────────────────────────────────────────────

  describe('DELETE /api/groups/:id/photo', () => {
    it('deletes a photo and clears DB fields', async () => {
      const group = await mkGroup('Laptops');

      // Upload first
      const uploadRes = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');
      expect(uploadRes.status).to.equal(200);

      const imgUrl = uploadRes.body.imageUrl;
      const thumbUrl = uploadRes.body.thumbnailUrl;

      // Delete
      const delRes = await request(app)
        .delete(`/api/groups/${group.id}/photo`);
      expect(delRes.status).to.equal(200);
      expect(delRes.body.success).to.be.true;

      // Verify DB fields cleared
      const updated = await ProductGroup.findById(group.id);
      expect(updated.imageUrl).to.be.null;
      expect(updated.thumbnailUrl).to.be.null;

      // Verify files removed from disk
      const imgPath = path.join(uploadsDir, 'groups', path.basename(imgUrl));
      const thumbPath = path.join(uploadsDir, 'groups', path.basename(thumbUrl));
      expect(fs.existsSync(imgPath)).to.be.false;
      expect(fs.existsSync(thumbPath)).to.be.false;
    });

    it('succeeds silently when no photo exists', async () => {
      const group = await mkGroup();

      const res = await request(app)
        .delete(`/api/groups/${group.id}/photo`);
      expect(res.status).to.equal(200);
      expect(res.body.success).to.be.true;
    });

    it('returns 403 when user is not admin', async () => {
      clerkMock.setRole('customer');
      const group = await mkGroup();

      const res = await request(app)
        .delete(`/api/groups/${group.id}/photo`);
      expect(res.status).to.equal(403);
    });
  });

  // ── Photo uploads for AssetTypes ────────────────────────────────────────────

  describe('POST /api/types/:id/photo', () => {
    it('uploads a photo for an asset type', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);

      const res = await request(app)
        .post(`/api/types/${type.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');

      expect(res.status).to.equal(200);
      expect(res.body.imageUrl).to.match(/^\/uploads\/types\/.+/);
      expect(res.body.thumbnailUrl).to.match(/^\/uploads\/types\/.+/);

      const updated = await AssetType.findById(type.id);
      expect(updated.imageUrl).to.equal(res.body.imageUrl);
    });

    it('returns 400 for invalid file type on types', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);

      const res = await request(app)
        .post(`/api/types/${type.id}/photo`)
        .attach('photo', Buffer.from('not an image'), { filename: 'test.txt', contentType: 'text/plain' });
      expect(res.status).to.equal(400);
    });
  });

  describe('DELETE /api/types/:id/photo', () => {
    it('deletes a photo from an asset type', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);

      await request(app)
        .post(`/api/types/${type.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');

      const delRes = await request(app)
        .delete(`/api/types/${type.id}/photo`);
      expect(delRes.status).to.equal(200);

      const updated = await AssetType.findById(type.id);
      expect(updated.imageUrl).to.be.null;
    });
  });

  // ── Photo uploads for Assets ────────────────────────────────────────────────

  describe('POST /api/assets/:id/photo', () => {
    it('uploads a photo for an asset', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);
      const asset = await mkAsset(type.id);

      const res = await request(app)
        .post(`/api/assets/${asset.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');

      expect(res.status).to.equal(200);
      expect(res.body.imageUrl).to.match(/^\/uploads\/assets\/.+/);
      expect(res.body.thumbnailUrl).to.match(/^\/uploads\/assets\/.+/);

      const updated = await Asset.findById(asset.id);
      expect(updated.imageUrl).to.equal(res.body.imageUrl);
    });

    it('returns 400 for invalid file type on assets', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);
      const asset = await mkAsset(type.id);

      const res = await request(app)
        .post(`/api/assets/${asset.id}/photo`)
        .attach('photo', Buffer.from('not an image'), { filename: 'test.txt', contentType: 'text/plain' });
      expect(res.status).to.equal(400);
    });
  });

  describe('DELETE /api/assets/:id/photo', () => {
    it('deletes a photo from an asset', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);
      const asset = await mkAsset(type.id);

      await request(app)
        .post(`/api/assets/${asset.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');

      const delRes = await request(app)
        .delete(`/api/assets/${asset.id}/photo`);
      expect(delRes.status).to.equal(200);

      const updated = await Asset.findById(asset.id);
      expect(updated.imageUrl).to.be.null;
    });
  });

  // ── Cascading delete with photos ────────────────────────────────────────────

  describe('Cascading delete with photos', () => {
    it('deletes photo files when a group with photos is deleted', async () => {
      const group = await mkGroup();

      const uploadRes = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');
      expect(uploadRes.status).to.equal(200);

      const imgUrl = uploadRes.body.imageUrl;
      const thumbUrl = uploadRes.body.thumbnailUrl;

      // Delete the group
      const delRes = await request(app).delete(`/api/groups/${group.id}`);
      expect(delRes.status).to.equal(200);

      // Photo files should be gone
      const imgPath = path.join(uploadsDir, 'groups', path.basename(imgUrl));
      const thumbPath = path.join(uploadsDir, 'groups', path.basename(thumbUrl));
      expect(fs.existsSync(imgPath)).to.be.false;
      expect(fs.existsSync(thumbPath)).to.be.false;
    });

    it('deletes photo files when a type with photos is deleted', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);

      const uploadRes = await request(app)
        .post(`/api/types/${type.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');
      expect(uploadRes.status).to.equal(200);

      const imgUrl = uploadRes.body.imageUrl;

      const delRes = await request(app).delete(`/api/types/${type.id}`);
      expect(delRes.status).to.equal(200);

      const imgPath = path.join(uploadsDir, 'types', path.basename(imgUrl));
      expect(fs.existsSync(imgPath)).to.be.false;
    });

    it('deletes photo files when an asset with photos is deleted', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);
      const asset = await mkAsset(type.id);

      const uploadRes = await request(app)
        .post(`/api/assets/${asset.id}/photo`)
        .attach('photo', MINI_JPEG, 'test.jpg');
      expect(uploadRes.status).to.equal(200);

      const imgUrl = uploadRes.body.imageUrl;

      const delRes = await request(app).delete(`/api/assets/${asset.id}`);
      expect(delRes.status).to.equal(200);

      const imgPath = path.join(uploadsDir, 'assets', path.basename(imgUrl));
      expect(fs.existsSync(imgPath)).to.be.false;
    });

    it('cascades photo deletion when deleting a group with child type and asset photos', async () => {
      const group = await mkGroup();
      const type  = await mkType(group.id);
      const asset = await mkAsset(type.id);

      // Upload photos to all three entities
      const groupRes = await request(app)
        .post(`/api/groups/${group.id}/photo`)
        .attach('photo', MINI_JPEG, 'group.jpg');
      expect(groupRes.status).to.equal(200);

      const typeRes = await request(app)
        .post(`/api/types/${type.id}/photo`)
        .attach('photo', MINI_JPEG, 'type.jpg');
      expect(typeRes.status).to.equal(200);

      const assetRes = await request(app)
        .post(`/api/assets/${asset.id}/photo`)
        .attach('photo', MINI_JPEG, 'asset.jpg');
      expect(assetRes.status).to.equal(200);

      const groupImg = groupRes.body.imageUrl;
      const typeImg  = typeRes.body.imageUrl;
      const assetImg = assetRes.body.imageUrl;

      // Delete the group — should cascade through type and asset
      const delRes = await request(app).delete(`/api/groups/${group.id}`);
      expect(delRes.status).to.equal(200);

      // All photo files should be gone
      const groupImgPath = path.join(uploadsDir, 'groups', path.basename(groupImg));
      const typeImgPath  = path.join(uploadsDir, 'types', path.basename(typeImg));
      const assetImgPath = path.join(uploadsDir, 'assets', path.basename(assetImg));

      expect(fs.existsSync(groupImgPath)).to.be.false;
      expect(fs.existsSync(typeImgPath)).to.be.false;
      expect(fs.existsSync(assetImgPath)).to.be.false;
    });
  });

  // ── PATCH /api/:entityType/:id (update entity name/description) ─────────────

  describe('PATCH /api/:entityType/:id', () => {
    it('updates a group name and description', async () => {
      const group = await mkGroup('Original Name');
      const res = await request(app)
        .patch(`/api/groups/${group.id}`)
        .send({ name: 'Updated Name', description: 'A new description' });
      expect(res.status).to.equal(200);
      expect(res.body.name).to.equal('Updated Name');
      expect(res.body.description).to.equal('A new description');
      // Verify DB
      const updated = await ProductGroup.findById(group.id);
      expect(updated.name).to.equal('Updated Name');
      expect(updated.description).to.equal('A new description');
    });

    it('updates only the description (name unchanged)', async () => {
      const group = await mkGroup('Keep This Name');
      const res = await request(app)
        .patch(`/api/groups/${group.id}`)
        .send({ description: 'Only description changed' });
      expect(res.status).to.equal(200);
      expect(res.body.name).to.equal('Keep This Name');
      expect(res.body.description).to.equal('Only description changed');
    });

    it('updates only the name (description unchanged)', async () => {
      const group = await mkGroup('Old Name');
      // Pre-set a description
      await ProductGroup.findByIdAndUpdate(group.id, { description: 'Existing desc' });
      const res = await request(app)
        .patch(`/api/groups/${group.id}`)
        .send({ name: 'New Name' });
      expect(res.status).to.equal(200);
      expect(res.body.name).to.equal('New Name');
      expect(res.body.description).to.equal('Existing desc');
    });

    it('returns 400 for empty name', async () => {
      const group = await mkGroup('Some Name');
      const res = await request(app)
        .patch(`/api/groups/${group.id}`)
        .send({ name: '   ' });
      expect(res.status).to.equal(400);
      expect(res.body.message).to.contain('Name cannot be empty');
    });

    it('returns 404 for non-existent ID', async () => {
      const res = await request(app)
        .patch('/api/groups/000000000000000000000000')
        .send({ name: 'Test' });
      expect(res.status).to.equal(404);
    });

    it('returns 401 when unauthenticated', async () => {
      clerkMock.setAuth(null);
      const group = await mkGroup('Test');
      const res = await request(app)
        .patch(`/api/groups/${group.id}`)
        .send({ name: 'Hack' });
      expect(res.status).to.equal(401);
    });

    it('returns 403 when non-admin', async () => {
      clerkMock.setRole('customer');
      const group = await mkGroup('Test');
      const res = await request(app)
        .patch(`/api/groups/${group.id}`)
        .send({ name: 'Hack' });
      expect(res.status).to.equal(403);
    });

    it('works for types', async () => {
      const group = await mkGroup();
      const type = await mkType(group.id, 'Old Type');
      const res = await request(app)
        .patch(`/api/types/${type.id}`)
        .send({ name: 'New Type', description: 'Type desc' });
      expect(res.status).to.equal(200);
      expect(res.body.name).to.equal('New Type');
      expect(res.body.description).to.equal('Type desc');
    });

    it('works for assets', async () => {
      const group = await mkGroup();
      const type = await mkType(group.id);
      const asset = await mkAsset(type.id, 'Old Asset');
      const res = await request(app)
        .patch(`/api/assets/${asset.id}`)
        .send({ name: 'New Asset', description: 'Asset desc' });
      expect(res.status).to.equal(200);
      expect(res.body.name).to.equal('New Asset');
      expect(res.body.description).to.equal('Asset desc');
    });

    it('description field appears in GET responses', async () => {
      const group = await ProductGroup.create({ name: 'Desc Group', description: 'test description' });
      const res = await request(app).get('/api/groups');
      expect(res.status).to.equal(200);
      const found = res.body.find(g => g.id === group.id);
      expect(found).to.exist;
      expect(found.description).to.equal('test description');
    });

    it('returns no description field when not set', async () => {
      const group = await ProductGroup.create({ name: 'No Desc' });
      const res = await request(app).get('/api/groups');
      expect(res.status).to.equal(200);
      const found = res.body.find(g => g.id === group.id);
      expect(found).to.exist;
      expect(found.description).to.equal('');
    });
  });
});
